Loading dataset

In [193]:
import pandas as pd
import numpy as np

In [194]:
sales_data = pd.read_csv('sales_data.csv')
sales_data.head(10)

,order_id,customer_id,product_id,quantity,unit_price,order_date,delivery_status,payment_method,region,discount_applied
0,O966977,C00397,P0022,3,39.25,06-07-2025,Delivered,PayPal,Central,0.00
1,O696648,C00236,P0023,5,18.92,06-07-2025,DELAYED,credit card,North,0.00
2,O202644,C00492,P0011,1,29.68,07-07-2025,delivered,Bank Transfer,North,0.15
3,O501803,C00031,P0003,1,32.76,08-07-2025,Cancelled,Credit Card,Central,0.20
4,O322242,C00495,P0016,1,47.62,08-07-2025,DELAYED,Credit Card,West,0.20
5,O190175,C00388,P0005,3,37.89,10-07-2025,Delayed,Bank Transfer,North,0.10
6,O272646,C00328,P0027,5,30.83,12-07-2025,delivered,PayPal,Central,0.05
7,O411881,C00201,P0019,3,12.56,14-07-2025,Delivered,Credit Card,East,0.00
8,O170570,C00076,P0030,3,28.32,16-07-2025,delivered,PayPal,Central,0.15
9,O619944,C00330,P0002,1,30.96,18-07-2025,DELAYED,Credit Card,South,0.15

In [195]:

customer_data = pd.read_csv('customer_info.csv')
customer_data

,customer_id,email,signup_date,gender,region,loyalty_tier
0,C00001,shaneramirez@gmail.com,26-04-25,Male,Central,Silver
1,C00002,jpeterson@bernard.com,11-08-24,Female,Central,gold
2,C00003,howardmaurice@yahoo.com,15-05-25,male,Central,gold
3,C00004,yherrera@arnold.org,14-06-25,FEMALE,Central,GOLD
4,C00005,janetwilliams@gmail.com,02-05-25,Male,West,bronze
...,...,...,...,...,...,...
495,C00496,simsjohn@wiley.net,19-02-25,femle,Central,GOLD
496,C00497,cameronwilliams@yahoo.com,30-12-24,NaN,West,GOLD
497,C00498,ibarron@yahoo.com,21-06-25,male,South,Silver
498,C00499,karen26@gmail.com,02-10-24,Female,North,gold
499,C00500,jasonjohnson@jackson.com,28-11-24,Male,North,gold

In [196]:
product_data = pd.read_csv('product_info.csv')
product_data.head(10)

,product_id,product_name,category,launch_date,base_price,supplier_code
0,P0001,Storage Product 39,Storage,11-03-25,15.88,S339
1,P0002,Cleaning Product 82,Cleaning,18-08-24,34.23,S974
2,P0003,Cleaning Product 85,Cleaning,15-07-24,7.92,S745
3,P0004,Kitchen Product 82,Kitchen,19-04-25,9.13,S589
4,P0005,Personal Care Product 1,Personal Care,20-10-24,31.10,S559
5,P0006,Cleaning Product 16,Cleaning,09-10-24,36.06,S980
6,P0007,Personal Care Product 64,Personal Care,30-09-24,33.63,S379
7,P0008,Storage Product 47,Storage,29-08-24,31.96,S788
8,P0009,Outdoors Product 13,Outdoors,18-04-25,8.00,S695
9,P0010,Cleaning Product 70,Cleaning,14-08-24,17.72,S321

Data cleaning

Standardise text formatting

In [197]:
sales_data['delivery_status']=sales_data['delivery_status'].str.strip().replace({'delivered':'Delivered','DELAYED':'Delayed','cancelled':'Cancelled','delrd':'Delivered','delyd':'Delayed'})
sales_data['payment_method']=sales_data['payment_method'].str.strip().replace({'credit card':'Credit Card','paypal':'PayPal','bank transfr':'Bank Transfer','cash':'Cash'})
sales_data['region']=sales_data['region'].str.strip().replace({'nrth':'North','south':'South','east':'East','west':'West'})
customer_data['gender']=customer_data['gender'].str.strip().replace({'MALE':'Male','FEMALE':'Female','male':'Male','female':'Female','femle':'Female'})
customer_data['loyalty_tier']=customer_data['loyalty_tier'].str.strip().replace({'BRONZE':'Bronze','bronze':'Bronze','SILVER':'Silver','silver':'Silver','sllver':'Silver','brnze':'Bronze','GOLD':'Gold','gold':'Gold','gld':'Gold','PLATINUM':'Platinum','platinum':'Platinum'})
customer_data['loyalty_tier'].value_counts()

loyalty_tier
Gold      265
Silver    119
Bronze    114
Name: count, dtype: int64

 Convert date columns

In [198]:
sales_data['order_date']=pd.to_datetime(sales_data['order_date'], errors='coerce')
sales_data['quantity']=pd.to_numeric(sales_data['quantity'], errors='coerce').astype('Int64')
customer_data['signup_date']=pd.to_datetime(customer_data['signup_date'], errors='coerce')
product_data['launch_date']=pd.to_datetime(product_data['launch_date'], errors='coerce')
product_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     30 non-null     str
 1   product_name   30 non-null     str
 2   category       30 non-null     str
 3   launch_date    30 non-null     datetime64[us]
 4   base_price     30 non-null     float64
 5   supplier_code  30 non-null     str
dtypes: datetime64[us](1), float64(1), str(4)
memory usage: 1.5 KB

/var/folders/ny/mvjvnvb130bdw8728wx5q__w0000gn/T/ipykernel_50699/3598727454.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  customer_data['signup_date']=pd.to_datetime(customer_data['signup_date'], errors='coerce')
/var/folders/ny/mvjvnvb130bdw8728wx5q__w0000gn/T/ipykernel_50699/3598727454.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  product_data['launch_date']=pd.to_datetime(product_data['launch_date'], errors='coerce')

 Handle missing values:

Sales data

In [199]:
sales_data.isnull().sum()
sales_data['delivery_status'] = sales_data['delivery_status'].fillna('Unknown')
sales_data['payment_method'] = sales_data['payment_method'].fillna('Unknown')
sales_data['region'] = sales_data['region'].fillna('Unknown')
sales_data['quantity'] = sales_data['quantity'].fillna(sales_data['quantity'].median())
sales_data['unit_price'] = sales_data['unit_price'].fillna(sales_data['unit_price'].median())
sales_data['discount_applied'] = sales_data['discount_applied'].fillna(0)

Customer data

In [200]:
customer_data.isnull().sum()
cols_to_fix = ['gender', 'region', 'loyalty_tier']
customer_data[cols_to_fix] = customer_data[cols_to_fix].fillna('Unknown')

Product data

In [201]:
product_data.isnull().sum()

product_id       0
product_name     0
category         0
launch_date      0
base_price       0
supplier_code    0
dtype: int64

Dropping NaN Values

 Sales Data


A sales record without order_id or product_id is statistical noise . keeping incomplete data slows down filtering operations and makes graphs less precise.

The order_date column was retained despite a high proportion of missing values (60.6%). Imputation was not performed due to the risk of introducing inaccurate time-based information. Instead, rows with valid dates were used selectively for analyses requiring temporal insights.

In [202]:

sales_data.dropna(subset=['order_id', 'customer_id', 'product_id'], inplace=True)
sales_data.isnull().sum()

order_id               0
customer_id            0
product_id             0
quantity               0
unit_price             0
order_date          1815
delivery_status        0
payment_method         0
region                 0
discount_applied       0
dtype: int64

Customer

The dataset contains minimal missing values across key variables, with less than 1% missing in customer_id, email, and signup_date. Rows with missing customer_id were removed due to their importance as unique identifiers, while other missing values were handled using appropriate imputation or left unchanged where they did not affect the analysis

In [203]:
customer_data['signup_date'] = customer_data['signup_date'].fillna(customer_data['signup_date'].median())
customer_data['email'] = customer_data['email'].fillna('Unknown')
customer_data = customer_data.dropna(subset=['customer_id'])

 Remove duplicates:

Sales Dataset

In [204]:
sales_data.drop_duplicates(subset=['order_id'],keep='first', inplace=True)
sales_data

,order_id,customer_id,product_id,quantity,unit_price,order_date,delivery_status,payment_method,region,discount_applied
0,O966977,C00397,P0022,3,39.25,2025-06-07,Delivered,PayPal,Central,0.00
1,O696648,C00236,P0023,5,18.92,2025-06-07,Delayed,Credit Card,North,0.00
2,O202644,C00492,P0011,1,29.68,2025-07-07,Delivered,Bank Transfer,North,0.15
3,O501803,C00031,P0003,1,32.76,2025-08-07,Cancelled,Credit Card,Central,0.20
4,O322242,C00495,P0016,1,47.62,2025-08-07,Delayed,Credit Card,West,0.20
...,...,...,...,...,...,...,...,...,...,...
2995,O868860,C00233,P0001,5,43.40,NaT,Delivered,Bank Transfer,West,0.20
2996,O949709,C00246,P0029,4,34.04,NaT,Delayed,Bank Transfer,West,0.20
2997,O763639,C00182,P0026,1,42.34,NaT,Delivered,Credit Card,South,0.00
2998,O753958,C00074,P0003,5,35.96,NaT,Delivered,Credit Card,Central,0.00
2999,O929624,C00405,P0004,3,43.23,2025-09-05,Delivered,Credit Card,West,0.10

Product

In [205]:
product_data.duplicated().sum()

np.int64(0)

Customer

In [206]:
customer_data.duplicated().sum()

np.int64(0)

 Validate numeric columns:

In [207]:
sales_data=sales_data[(sales_data['quantity'] >0) &(sales_data['unit_price'] >0)& (sales_data['discount_applied']>0)]
sales_data

,order_id,customer_id,product_id,quantity,unit_price,order_date,delivery_status,payment_method,region,discount_applied
2,O202644,C00492,P0011,1,29.68,2025-07-07,Delivered,Bank Transfer,North,0.15
3,O501803,C00031,P0003,1,32.76,2025-08-07,Cancelled,Credit Card,Central,0.20
4,O322242,C00495,P0016,1,47.62,2025-08-07,Delayed,Credit Card,West,0.20
5,O190175,C00388,P0005,3,37.89,2025-10-07,Delayed,Bank Transfer,North,0.10
6,O272646,C00328,P0027,5,30.83,2025-12-07,Delivered,PayPal,Central,0.05
...,...,...,...,...,...,...,...,...,...,...
2993,O517776,C00138,P0024,3,17.92,2025-10-05,Cancelled,Credit Card,North,0.15
2994,O650396,C00298,P0005,2,21.88,2025-11-05,Delayed,Bank Transfer,Central,0.20
2995,O868860,C00233,P0001,5,43.40,NaT,Delivered,Bank Transfer,West,0.20
2996,O949709,C00246,P0029,4,34.04,NaT,Delayed,Bank Transfer,West,0.20
2999,O929624,C00405,P0004,3,43.23,2025-09-05,Delivered,Credit Card,West,0.10

In [209]:
product_data[product_data['base_price'] >= 0 ]

,product_id,product_name,category,launch_date,base_price,supplier_code
0,P0001,Storage Product 39,Storage,2025-11-03,15.88,S339
1,P0002,Cleaning Product 82,Cleaning,2024-08-18,34.23,S974
2,P0003,Cleaning Product 85,Cleaning,2024-07-15,7.92,S745
3,P0004,Kitchen Product 82,Kitchen,2025-04-19,9.13,S589
4,P0005,Personal Care Product 1,Personal Care,2024-10-20,31.10,S559
5,P0006,Cleaning Product 16,Cleaning,2024-09-10,36.06,S980
6,P0007,Personal Care Product 64,Personal Care,2024-09-30,33.63,S379
7,P0008,Storage Product 47,Storage,2024-08-29,31.96,S788
8,P0009,Outdoors Product 13,Outdoors,2025-04-18,8.00,S695
9,P0010,Cleaning Product 70,Cleaning,2024-08-14,17.72,S321
10,P0011,Kitchen Product 53,Kitchen,2025-03-25,11.08,S645
11,P0012,Cleaning Product 29,Cleaning,2025-04-19,14.67,S481
12,P0013,Cleaning Product 94,Cleaning,2025-06-17,36.52,S914
13,P0014,Outdoors Product 91,Outdoors,2025-02-02,13.22,S876
14,P0015,Storage Product 10,Storage,2024-08-08,39.21,S466
15,P0016,Cleaning Product 53,Cleaning,2025-02-20,26.71,S715
16,P0017,Personal Care Product 11,Personal Care,2024-12-16,16.46,S594
17,P0018,Storage Product 37,Storage,2024-07-18,6.08,S767
18,P0019,Kitchen Product 42,Kitchen,2024-07-17,30.30,S993
19,P0020,Cleaning Product 40,Cleaning,2024-11-08,30.27,S492
20,P0021,Kitchen Product 70,Kitchen,2024-09-28,20.23,S643
21,P0022,Cleaning Product 86,Cleaning,2024-04-10,19.77,S924
22,P0023,Outdoors Product 32,Outdoors,2025-01-18,36.04,S907
23,P0024,Storage Product 87,Storage,2025-02-24,26.33,S558
24,P0025,Cleaning Product 84,Cleaning,2024-07-16,15.24,S503
25,P0026,Storage Product 50,Storage,2025-08-02,27.06,S952
26,P0027,Outdoors Product 55,Outdoors,2024-09-21,23.05,S127
27,P0028,Outdoors Product 53,Outdoors,2025-10-04,34.28,S587
28,P0029,Cleaning Product 69,Cleaning,2025-03-15,23.41,S424
29,P0030,Cleaning Product 72,Cleaning,2025-04-04,9.77,S455

3. Merge the Data

In [214]:
merged_data = pd.merge(sales_data, product_data, on='product_id', how='left')
merged_df= pd.merge(merged_data, customer_data, on='customer_id', how='left')

In [215]:
merged_df.head(10)

,order_id,customer_id,product_id,quantity,unit_price,order_date,delivery_status,payment_method,region_x,discount_applied,product_name,category,launch_date,base_price,supplier_code,email,signup_date,gender,region_y,loyalty_tier
0,O202644,C00492,P0011,1,29.68,2025-07-07,Delivered,Bank Transfer,North,0.15,Kitchen Product 53,Kitchen,2025-03-25,11.08,S645,lcook@walters-smith.com,2024-09-25,Male,Central,Gold
1,O501803,C00031,P0003,1,32.76,2025-08-07,Cancelled,Credit Card,Central,0.20,Cleaning Product 85,Cleaning,2024-07-15,7.92,S745,smoore@gmail.com,2024-07-28,Female,Central,Gold
2,O322242,C00495,P0016,1,47.62,2025-08-07,Delayed,Credit Card,West,0.20,Cleaning Product 53,Cleaning,2025-02-20,26.71,S715,mcclainkatherine@hotmail.com,2024-09-18,Male,Central,Gold
3,O190175,C00388,P0005,3,37.89,2025-10-07,Delayed,Bank Transfer,North,0.10,Personal Care Product 1,Personal Care,2024-10-20,31.10,S559,abbottdominique@yahoo.com,2024-09-23,Male,North,Gold
4,O272646,C00328,P0027,5,30.83,2025-12-07,Delivered,PayPal,Central,0.05,Outdoors Product 55,Outdoors,2024-09-21,23.05,S127,adamsnorman@moore.com,2024-08-07,Female,Central,Gold
5,O170570,C00076,P0030,3,28.32,NaT,Delivered,PayPal,Central,0.15,Cleaning Product 72,Cleaning,2025-04-04,9.77,S455,jeffrey10@herring.com,2025-04-03,Female,North,Gold
6,O619944,C00330,P0002,1,30.96,NaT,Delayed,Credit Card,South,0.15,Cleaning Product 82,Cleaning,2024-08-18,34.23,S974,ryanhawkins@russell.com,2025-02-22,Other,West,Bronze
7,O865247,C00249,P0022,5,30.92,NaT,Delayed,Credit Card,East,0.10,Cleaning Product 86,Cleaning,2024-04-10,19.77,S924,theresalong@grant-diaz.com,2024-09-21,Male,South,Gold
8,O315552,C00110,P0007,4,28.74,NaT,Delivered,Bank Transfer,North,0.10,Personal Care Product 64,Personal Care,2024-09-30,33.63,S379,harrisonricky@yahoo.com,2025-03-23,Female,South,Gold
9,O305482,C00404,P0003,4,9.79,NaT,Cancelled,Bank Transfer,North,0.15,Cleaning Product 85,Cleaning,2024-07-15,7.92,S745,shawrachel@gmail.com,2024-09-30,Male,East,Gold

In [216]:
merged_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1995 entries, 0 to 1994
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1995 non-null   str
 1   customer_id       1995 non-null   str
 2   product_id        1995 non-null   str
 3   quantity          1995 non-null   Int64
 4   unit_price        1995 non-null   float64
 5   order_date        783 non-null    datetime64[us]
 6   delivery_status   1995 non-null   str
 7   payment_method    1995 non-null   str
 8   region_x          1995 non-null   str
 9   discount_applied  1995 non-null   float64
 10  product_name      1995 non-null   str
 11  category          1995 non-null   str
 12  launch_date       1995 non-null   datetime64[us]
 13  base_price        1995 non-null   float64
 14  supplier_code     1995 non-null   str
 15  email             1980 non-null   str
 16  signup_date       1980 non-null   datetime64[us]
 17  gender            1980 non-null   str
 18  region_y          1980 non-null   str
 19  loyalty_tier      1980 non-null   str
dtypes: Int64(1), datetime64[us](3), float64(3), str(13)
memory usage: 313.8 KB

4. Feature Engineering

4.1 revenue = quantity × unit_price × (1 - discount_applied)

In [217]:
merged_df['revenue'] = merged_df['quantity'] * merged_df['unit_price'] * (1 - merged_df['discount_applied'])
merged_df.head(10)

,order_id,customer_id,product_id,quantity,unit_price,order_date,delivery_status,payment_method,region_x,discount_applied,...,category,launch_date,base_price,supplier_code,email,signup_date,gender,region_y,loyalty_tier,revenue
0,O202644,C00492,P0011,1,29.68,2025-07-07,Delivered,Bank Transfer,North,0.15,...,Kitchen,2025-03-25,11.08,S645,lcook@walters-smith.com,2024-09-25,Male,Central,Gold,25.228
1,O501803,C00031,P0003,1,32.76,2025-08-07,Cancelled,Credit Card,Central,0.20,...,Cleaning,2024-07-15,7.92,S745,smoore@gmail.com,2024-07-28,Female,Central,Gold,26.208
2,O322242,C00495,P0016,1,47.62,2025-08-07,Delayed,Credit Card,West,0.20,...,Cleaning,2025-02-20,26.71,S715,mcclainkatherine@hotmail.com,2024-09-18,Male,Central,Gold,38.096
3,O190175,C00388,P0005,3,37.89,2025-10-07,Delayed,Bank Transfer,North,0.10,...,Personal Care,2024-10-20,31.10,S559,abbottdominique@yahoo.com,2024-09-23,Male,North,Gold,102.303
4,O272646,C00328,P0027,5,30.83,2025-12-07,Delivered,PayPal,Central,0.05,...,Outdoors,2024-09-21,23.05,S127,adamsnorman@moore.com,2024-08-07,Female,Central,Gold,146.4425
5,O170570,C00076,P0030,3,28.32,NaT,Delivered,PayPal,Central,0.15,...,Cleaning,2025-04-04,9.77,S455,jeffrey10@herring.com,2025-04-03,Female,North,Gold,72.216
6,O619944,C00330,P0002,1,30.96,NaT,Delayed,Credit Card,South,0.15,...,Cleaning,2024-08-18,34.23,S974,ryanhawkins@russell.com,2025-02-22,Other,West,Bronze,26.316
7,O865247,C00249,P0022,5,30.92,NaT,Delayed,Credit Card,East,0.10,...,Cleaning,2024-04-10,19.77,S924,theresalong@grant-diaz.com,2024-09-21,Male,South,Gold,139.14
8,O315552,C00110,P0007,4,28.74,NaT,Delivered,Bank Transfer,North,0.10,...,Personal Care,2024-09-30,33.63,S379,harrisonricky@yahoo.com,2025-03-23,Female,South,Gold,103.464
9,O305482,C00404,P0003,4,9.79,NaT,Cancelled,Bank Transfer,North,0.15,...,Cleaning,2024-07-15,7.92,S745,shawrachel@gmail.com,2024-09-30,Male,East,Gold,33.286

4.2 order_week = ISO week from order_date

In [232]:
merged_df['order_week'] = merged_df['order_date'].dt.isocalendar().week
merged_df

,order_id,customer_id,product_id,quantity,unit_price,order_date,delivery_status,payment_method,region_x,discount_applied,...,email,signup_date,gender,region_y,loyalty_tier,revenue,price_band,is_late_delivery,days_to_order,order_week
0,O202644,C00492,P0011,1,29.68,2025-07-07,Delivered,Bank Transfer,North,0.15,...,lcook@walters-smith.com,2024-09-25,Male,Central,Gold,25.228,Medium,False,104.0,28
1,O501803,C00031,P0003,1,32.76,2025-08-07,Cancelled,Credit Card,Central,0.20,...,smoore@gmail.com,2024-07-28,Female,Central,Gold,26.208,High,False,388.0,32
2,O322242,C00495,P0016,1,47.62,2025-08-07,Delayed,Credit Card,West,0.20,...,mcclainkatherine@hotmail.com,2024-09-18,Male,Central,Gold,38.096,High,True,168.0,32
3,O190175,C00388,P0005,3,37.89,2025-10-07,Delayed,Bank Transfer,North,0.10,...,abbottdominique@yahoo.com,2024-09-23,Male,North,Gold,102.303,High,True,352.0,41
4,O272646,C00328,P0027,5,30.83,2025-12-07,Delivered,PayPal,Central,0.05,...,adamsnorman@moore.com,2024-08-07,Female,Central,Gold,146.4425,High,False,442.0,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1990,O517776,C00138,P0024,3,17.92,2025-10-05,Cancelled,Credit Card,North,0.15,...,erica21@lucas.org,2024-11-24,Female,East,Gold,45.696,Medium,False,223.0,40
1991,O650396,C00298,P0005,2,21.88,2025-11-05,Delayed,Bank Transfer,Central,0.20,...,melissaturner@hotmail.com,2024-08-31,Female,East,Bronze,35.008,Medium,True,381.0,45
1992,O868860,C00233,P0001,5,43.40,NaT,Delivered,Bank Transfer,West,0.20,...,ryanbartlett@guerra.com,2024-01-11,Other,Central,Silver,173.6,High,False,NaN,<NA>
1993,O949709,C00246,P0029,4,34.04,NaT,Delayed,Bank Transfer,West,0.20,...,brandywilliams@simpson-khan.info,2024-10-24,Male,South,Gold,108.928,High,True,NaN,<NA>
1994,O929624,C00405,P0004,3,43.23,2025-09-05,Delivered,Credit Card,West,0.10,...,djones@ayala-collins.com,2025-05-02,Other,West,Silver,116.721,High,False,139.0,36

4.3 price_band = Categorise unit price as Low (<£15), Medium (£15–30), High (>£30)

In [223]:
merged_df['price_band']=pd.cut(merged_df['unit_price'], bins=[0, 15, 30, np.inf], labels=['Low', 'Medium', 'High'])
merged_df

,order_id,customer_id,product_id,quantity,unit_price,order_date,delivery_status,payment_method,region_x,discount_applied,...,launch_date,base_price,supplier_code,email,signup_date,gender,region_y,loyalty_tier,revenue,price_band
0,O202644,C00492,P0011,1,29.68,2025-07-07,Delivered,Bank Transfer,North,0.15,...,2025-03-25,11.08,S645,lcook@walters-smith.com,2024-09-25,Male,Central,Gold,25.228,Medium
1,O501803,C00031,P0003,1,32.76,2025-08-07,Cancelled,Credit Card,Central,0.20,...,2024-07-15,7.92,S745,smoore@gmail.com,2024-07-28,Female,Central,Gold,26.208,High
2,O322242,C00495,P0016,1,47.62,2025-08-07,Delayed,Credit Card,West,0.20,...,2025-02-20,26.71,S715,mcclainkatherine@hotmail.com,2024-09-18,Male,Central,Gold,38.096,High
3,O190175,C00388,P0005,3,37.89,2025-10-07,Delayed,Bank Transfer,North,0.10,...,2024-10-20,31.10,S559,abbottdominique@yahoo.com,2024-09-23,Male,North,Gold,102.303,High
4,O272646,C00328,P0027,5,30.83,2025-12-07,Delivered,PayPal,Central,0.05,...,2024-09-21,23.05,S127,adamsnorman@moore.com,2024-08-07,Female,Central,Gold,146.4425,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1990,O517776,C00138,P0024,3,17.92,2025-10-05,Cancelled,Credit Card,North,0.15,...,2025-02-24,26.33,S558,erica21@lucas.org,2024-11-24,Female,East,Gold,45.696,Medium
1991,O650396,C00298,P0005,2,21.88,2025-11-05,Delayed,Bank Transfer,Central,0.20,...,2024-10-20,31.10,S559,melissaturner@hotmail.com,2024-08-31,Female,East,Bronze,35.008,Medium
1992,O868860,C00233,P0001,5,43.40,NaT,Delivered,Bank Transfer,West,0.20,...,2025-11-03,15.88,S339,ryanbartlett@guerra.com,2024-01-11,Other,Central,Silver,173.6,High
1993,O949709,C00246,P0029,4,34.04,NaT,Delayed,Bank Transfer,West,0.20,...,2025-03-15,23.41,S424,brandywilliams@simpson-khan.info,2024-10-24,Male,South,Gold,108.928,High
1994,O929624,C00405,P0004,3,43.23,2025-09-05,Delivered,Credit Card,West,0.10,...,2025-04-19,9.13,S589,djones@ayala-collins.com,2025-05-02,Other,West,Silver,116.721,High

4.4 days_to_order = Days between launch_date and order_date

In [228]:
merged_df['days_to_order'] = (merged_df['order_date'] - merged_df['launch_date']).dt.days
merged_df

,order_id,customer_id,product_id,quantity,unit_price,order_date,delivery_status,payment_method,region_x,discount_applied,...,supplier_code,email,signup_date,gender,region_y,loyalty_tier,revenue,price_band,is_late_delivery,days_to_order
0,O202644,C00492,P0011,1,29.68,2025-07-07,Delivered,Bank Transfer,North,0.15,...,S645,lcook@walters-smith.com,2024-09-25,Male,Central,Gold,25.228,Medium,False,104.0
1,O501803,C00031,P0003,1,32.76,2025-08-07,Cancelled,Credit Card,Central,0.20,...,S745,smoore@gmail.com,2024-07-28,Female,Central,Gold,26.208,High,False,388.0
2,O322242,C00495,P0016,1,47.62,2025-08-07,Delayed,Credit Card,West,0.20,...,S715,mcclainkatherine@hotmail.com,2024-09-18,Male,Central,Gold,38.096,High,True,168.0
3,O190175,C00388,P0005,3,37.89,2025-10-07,Delayed,Bank Transfer,North,0.10,...,S559,abbottdominique@yahoo.com,2024-09-23,Male,North,Gold,102.303,High,True,352.0
4,O272646,C00328,P0027,5,30.83,2025-12-07,Delivered,PayPal,Central,0.05,...,S127,adamsnorman@moore.com,2024-08-07,Female,Central,Gold,146.4425,High,False,442.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1990,O517776,C00138,P0024,3,17.92,2025-10-05,Cancelled,Credit Card,North,0.15,...,S558,erica21@lucas.org,2024-11-24,Female,East,Gold,45.696,Medium,False,223.0
1991,O650396,C00298,P0005,2,21.88,2025-11-05,Delayed,Bank Transfer,Central,0.20,...,S559,melissaturner@hotmail.com,2024-08-31,Female,East,Bronze,35.008,Medium,True,381.0
1992,O868860,C00233,P0001,5,43.40,NaT,Delivered,Bank Transfer,West,0.20,...,S339,ryanbartlett@guerra.com,2024-01-11,Other,Central,Silver,173.6,High,False,NaN
1993,O949709,C00246,P0029,4,34.04,NaT,Delayed,Bank Transfer,West,0.20,...,S424,brandywilliams@simpson-khan.info,2024-10-24,Male,South,Gold,108.928,High,True,NaN
1994,O929624,C00405,P0004,3,43.23,2025-09-05,Delivered,Credit Card,West,0.10,...,S589,djones@ayala-collins.com,2025-05-02,Other,West,Silver,116.721,High,False,139.0

4.5 email_domain = Extract domain from email (e.g., gmail.com)

In [234]:
merged_df['email_domain'] = merged_df['email'].str.split('@').str[1]
merged_df.head(10)

,order_id,customer_id,product_id,quantity,unit_price,order_date,delivery_status,payment_method,region_x,discount_applied,...,signup_date,gender,region_y,loyalty_tier,revenue,price_band,is_late_delivery,days_to_order,order_week,email_domain
0,O202644,C00492,P0011,1,29.68,2025-07-07,Delivered,Bank Transfer,North,0.15,...,2024-09-25,Male,Central,Gold,25.228,Medium,False,104.0,28,walters-smith.com
1,O501803,C00031,P0003,1,32.76,2025-08-07,Cancelled,Credit Card,Central,0.20,...,2024-07-28,Female,Central,Gold,26.208,High,False,388.0,32,gmail.com
2,O322242,C00495,P0016,1,47.62,2025-08-07,Delayed,Credit Card,West,0.20,...,2024-09-18,Male,Central,Gold,38.096,High,True,168.0,32,hotmail.com
3,O190175,C00388,P0005,3,37.89,2025-10-07,Delayed,Bank Transfer,North,0.10,...,2024-09-23,Male,North,Gold,102.303,High,True,352.0,41,yahoo.com
4,O272646,C00328,P0027,5,30.83,2025-12-07,Delivered,PayPal,Central,0.05,...,2024-08-07,Female,Central,Gold,146.4425,High,False,442.0,49,moore.com
5,O170570,C00076,P0030,3,28.32,NaT,Delivered,PayPal,Central,0.15,...,2025-04-03,Female,North,Gold,72.216,Medium,False,NaN,<NA>,herring.com
6,O619944,C00330,P0002,1,30.96,NaT,Delayed,Credit Card,South,0.15,...,2025-02-22,Other,West,Bronze,26.316,High,True,NaN,<NA>,russell.com
7,O865247,C00249,P0022,5,30.92,NaT,Delayed,Credit Card,East,0.10,...,2024-09-21,Male,South,Gold,139.14,High,True,NaN,<NA>,grant-diaz.com
8,O315552,C00110,P0007,4,28.74,NaT,Delivered,Bank Transfer,North,0.10,...,2025-03-23,Female,South,Gold,103.464,Medium,False,NaN,<NA>,yahoo.com
9,O305482,C00404,P0003,4,9.79,NaT,Cancelled,Bank Transfer,North,0.15,...,2024-09-30,Male,East,Gold,33.286,Low,False,NaN,<NA>,gmail.com

4.6 is_late = True if delivery_status is "Delayed"

In [225]:
merged_df['is_late_delivery'] = merged_df['delivery_status'].apply(lambda x: True if x == 'Delayed' else False)
merged_df.head(10)

,order_id,customer_id,product_id,quantity,unit_price,order_date,delivery_status,payment_method,region_x,discount_applied,...,base_price,supplier_code,email,signup_date,gender,region_y,loyalty_tier,revenue,price_band,is_late_delivery
0,O202644,C00492,P0011,1,29.68,2025-07-07,Delivered,Bank Transfer,North,0.15,...,11.08,S645,lcook@walters-smith.com,2024-09-25,Male,Central,Gold,25.228,Medium,False
1,O501803,C00031,P0003,1,32.76,2025-08-07,Cancelled,Credit Card,Central,0.20,...,7.92,S745,smoore@gmail.com,2024-07-28,Female,Central,Gold,26.208,High,False
2,O322242,C00495,P0016,1,47.62,2025-08-07,Delayed,Credit Card,West,0.20,...,26.71,S715,mcclainkatherine@hotmail.com,2024-09-18,Male,Central,Gold,38.096,High,True
3,O190175,C00388,P0005,3,37.89,2025-10-07,Delayed,Bank Transfer,North,0.10,...,31.10,S559,abbottdominique@yahoo.com,2024-09-23,Male,North,Gold,102.303,High,True
4,O272646,C00328,P0027,5,30.83,2025-12-07,Delivered,PayPal,Central,0.05,...,23.05,S127,adamsnorman@moore.com,2024-08-07,Female,Central,Gold,146.4425,High,False
5,O170570,C00076,P0030,3,28.32,NaT,Delivered,PayPal,Central,0.15,...,9.77,S455,jeffrey10@herring.com,2025-04-03,Female,North,Gold,72.216,Medium,False
6,O619944,C00330,P0002,1,30.96,NaT,Delayed,Credit Card,South,0.15,...,34.23,S974,ryanhawkins@russell.com,2025-02-22,Other,West,Bronze,26.316,High,True
7,O865247,C00249,P0022,5,30.92,NaT,Delayed,Credit Card,East,0.10,...,19.77,S924,theresalong@grant-diaz.com,2024-09-21,Male,South,Gold,139.14,High,True
8,O315552,C00110,P0007,4,28.74,NaT,Delivered,Bank Transfer,North,0.10,...,33.63,S379,harrisonricky@yahoo.com,2025-03-23,Female,South,Gold,103.464,Medium,False
9,O305482,C00404,P0003,4,9.79,NaT,Cancelled,Bank Transfer,North,0.15,...,7.92,S745,shawrachel@gmail.com,2024-09-30,Male,East,Gold,33.286,Low,False

5. Create Summary Tables

In [243]:
merged_df.pivot_table(index='region_y', values='revenue', aggfunc='sum').sort_values(by='revenue', ascending=False)

             revenue
region_y
West      32366.2785
North      31985.194
East      31550.2885
South     28638.6965
Central    27671.211
Unknown      935.273

Product category performance (revenue, quantity, discount)

In [253]:

measures=['revenue','quantity','discount_applied']

merged_df.groupby(['category'])[measures].sum().sort_values(by='revenue', ascending=False)

                  revenue  quantity  discount_applied
category
Cleaning       61708.7075      2453            103.00
Storage        29413.0575      1151             46.60
Outdoors          26649.6      1032             41.65
Kitchen         20268.586       757             30.40
Personal Care  15816.5365       598             26.20

In [252]:
merged_df.pivot_table(index='category', values=['revenue', 'quantity', 'discount_applied'], aggfunc='sum').sort_values(by='revenue', ascending=False)

               discount_applied  quantity     revenue
category
Cleaning                 103.00      2453  61708.7075
Storage                   46.60      1151  29413.0575
Outdoors                  41.65      1032     26649.6
Kitchen                   30.40       757   20268.586
Personal Care             26.20       598  15816.5365

Customer behaviour by loyalty_tier and signup_month

Extract the month name from the sign up date

In [257]:

merged_df['month_name'] = merged_df['signup_date'].dt.month_name()
merged_df

,order_id,customer_id,product_id,quantity,unit_price,order_date,delivery_status,payment_method,region_x,discount_applied,...,loyalty_tier,revenue,price_band,is_late_delivery,days_to_order,order_week,email_domain,signup_month,signup_month_name,month_name
0,O202644,C00492,P0011,1,29.68,2025-07-07,Delivered,Bank Transfer,North,0.15,...,Gold,25.228,Medium,False,104.0,28,walters-smith.com,9.0,September,September
1,O501803,C00031,P0003,1,32.76,2025-08-07,Cancelled,Credit Card,Central,0.20,...,Gold,26.208,High,False,388.0,32,gmail.com,7.0,July,July
2,O322242,C00495,P0016,1,47.62,2025-08-07,Delayed,Credit Card,West,0.20,...,Gold,38.096,High,True,168.0,32,hotmail.com,9.0,September,September
3,O190175,C00388,P0005,3,37.89,2025-10-07,Delayed,Bank Transfer,North,0.10,...,Gold,102.303,High,True,352.0,41,yahoo.com,9.0,September,September
4,O272646,C00328,P0027,5,30.83,2025-12-07,Delivered,PayPal,Central,0.05,...,Gold,146.4425,High,False,442.0,49,moore.com,8.0,August,August
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1990,O517776,C00138,P0024,3,17.92,2025-10-05,Cancelled,Credit Card,North,0.15,...,Gold,45.696,Medium,False,223.0,40,lucas.org,11.0,November,November
1991,O650396,C00298,P0005,2,21.88,2025-11-05,Delayed,Bank Transfer,Central,0.20,...,Bronze,35.008,Medium,True,381.0,45,hotmail.com,8.0,August,August
1992,O868860,C00233,P0001,5,43.40,NaT,Delivered,Bank Transfer,West,0.20,...,Silver,173.6,High,False,NaN,<NA>,guerra.com,1.0,January,January
1993,O949709,C00246,P0029,4,34.04,NaT,Delayed,Bank Transfer,West,0.20,...,Gold,108.928,High,True,NaN,<NA>,simpson-khan.info,10.0,October,October
1994,O929624,C00405,P0004,3,43.23,2025-09-05,Delivered,Credit Card,West,0.10,...,Silver,116.721,High,False,139.0,36,ayala-collins.com,5.0,May,May

In [264]:

merged_df.groupby(['month_name','loyalty_tier'])['revenue'].sum().unstack()

loyalty_tier     Bronze        Gold     Silver  Unknown
month_name
April         1078.7005    7863.874   3606.395     <NA>
August         2444.931   6047.4625  2079.2425     <NA>
December        2696.11    8425.897  1026.4295     <NA>
February       3165.436    6420.125  2596.1165  262.207
January        1409.861   7766.3655   2809.103     <NA>
July          1826.8695   7311.4785  1866.4095     <NA>
June          3525.7965    4490.191   3606.043     <NA>
March          3070.672   4655.9015  4610.3615     <NA>
May           2332.4945   5719.1125   3443.532  356.966
November       2783.973    7961.623   4744.737     <NA>
October        3357.268    8929.758  3794.6745     <NA>
September     2192.1845  11051.2835   1817.356     <NA>

In [266]:
merged_df.pivot_table(index='month_name', columns='loyalty_tier', values='revenue', aggfunc='sum')

loyalty_tier     Bronze        Gold     Silver  Unknown
month_name
April         1078.7005    7863.874   3606.395     <NA>
August         2444.931   6047.4625  2079.2425     <NA>
December        2696.11    8425.897  1026.4295     <NA>
February       3165.436    6420.125  2596.1165  262.207
January        1409.861   7766.3655   2809.103     <NA>
July          1826.8695   7311.4785  1866.4095     <NA>
June          3525.7965    4490.191   3606.043     <NA>
March          3070.672   4655.9015  4610.3615     <NA>
May           2332.4945   5719.1125   3443.532  356.966
November       2783.973    7961.623   4744.737     <NA>
October        3357.268    8929.758  3794.6745     <NA>
September     2192.1845  11051.2835   1817.356     <NA>

Delivery performance by region and price_band

In [275]:
cat=['price_band', 'region_y']
merged_df.groupby(['delivery_status'])[cat].value_counts().unstack(fill_value=0)

region_y                    Central  East  North  South  Unknown  West
delivery_status price_band
Cancelled       Low              16    15      8     14        0    15
                Medium           35    24     21     28        0    32
                High             21    41     41     31        2    38
Delayed         Low              23    20     29     31        0    23
                Medium           58    46     49     57        1    76
                High             71    73     84     69        1    81
Delivered       Low              26    28     25     18        1    31
                Medium           59    66     63     59        0    46
                High             73    85     80     59        4    82
Unknown         Low               0     0      0      0        0     0
                Medium            0     0      0      0        0     0
                High              0     1      0      0        0     0

In [302]:

delivery_analysis = merged_df.groupby(['region_y', 'price_band'])['is_late_delivery'].agg(['mean', 'count'])  


delivery_analysis['delay_rate_%'] = (delivery_analysis['mean'] * 100).round(2)
delivery_analysis.rename(columns={'count': 'total_orders'}, inplace=True)
delivery_analysis.drop(columns=['mean'], inplace=True)


delivery_analysis.unstack(fill_value=0)

           total_orders             delay_rate_%
price_band          Low Medium High          Low  Medium   High
region_y
Central              65    152  165        35.38   38.16  43.03
East                 63    136  200        31.75   33.82  36.50
North                62    133  205        46.77   36.84  40.98
South                63    144  159        49.21   39.58  43.40
Unknown               1      1    7         0.00  100.00  14.29
West                 69    154  201        33.33   49.35  40.30

Preferred payment methods by loyalty_tier

In [304]:
preferred_payment_methods = merged_df.groupby('loyalty_tier')['payment_method'].value_counts().unstack(fill_value=0)
preferred_payment_methods

payment_method  Bank Transfer  Credit Card  PayPal  Unknown
loyalty_tier
Bronze                    122          181      99        0
Gold                      257          562     285        2
Silver                    135          224     106        1
Unknown                     0            5       1        0